package dev.arubik.craftengine.script;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Plain-Java support routines called BY the classes {@link PolyClassGenerator} generates. Every
 * method here exists so the generated bytecode can stay small and obviously-correct: resolution and
 * shape-validation logic lives in readable Java, not in hand-emitted ASM.
 *
 * <p>Two jobs:
 * <ul>
 *   <li><b>Resolution</b> ({@code resolveTypedHandler}/{@code resolveMethodHandler}/{@code
 *       resolvePropertyHandler}) — called from a generated wrapper's {@code refresh()}, which runs
 *       once at generation time and again after EVERY {@link PolyTypeRegistry} mutation. Resolution
 *       is always by NAME, so a wrapper follows re-registrations instead of pinning whatever object
 *       happened to be registered when it was generated.
 *   <li><b>Generic fallback</b> ({@code genericCall}/{@code genericProperty}) — what a generated
 *       method does when its cached handler is {@code null}, i.e. the member no longer exists or
 *       (for a typed method) its registered shape no longer matches the native signature this
 *       wrapper was generated with. Falls back to exactly the dispatch the non-specialized path
 *       would have done, so a shape change degrades to correct-but-slower, never to wrong.
 * </ul>
 */
public final class PolyClassRuntime {

    private PolyClassRuntime() {}

    /** One character per {@link PolyClassGenerator.Kind}: the shape a generated method was built
     *  for. {@code refresh()} passes the signature it was generated with, and resolution refuses
     *  (returns null -> generic fallback) if the CURRENT registration disagrees. */
    static char kindChar(PolyClassGenerator.Kind k) {
        return switch (k) {
            case DOUBLE -> 'D';
            case BOOL -> 'Z';
            case STRING -> 'S';
            case RAW -> 'R';
            case LIST -> 'L';
            case UNKNOWN -> '?';
        };
    }

    private static char kindCharOf(PolyType.TypeCodec<?> codec) {
        return kindChar(PolyClassGenerator.kindOf(codec));
    }

    /**
     * Resolves the typed handler for {@code typeName.method}, but ONLY if its currently-registered
     * shape still exactly matches {@code sig} (the arg-kind characters, then {@code ':'}, then the
     * return-kind character — the signature the calling wrapper's native method was generated for).
     * Any mismatch — type gone, method gone, now untyped, different arity, a codec swapped — returns
     * null, which routes that wrapper method through {@link #genericCall} instead.
     */
    public static Object resolveTypedHandler(String typeName, String method, String sig) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return null;
        PolyType.TypedMethodDescriptor d = type.resolveTypedMethod(method);
        if (d == null) return null;
        int colon = sig.indexOf(':');
        if (colon < 0) return null;
        String argSig = sig.substring(0, colon);
        String retSig = sig.substring(colon + 1);
        if (d.arity() != argSig.length() || retSig.length() != 1) return null;
        for (int i = 0; i < argSig.length(); i++) {
            if (kindCharOf(d.argTypes().get(i)) != argSig.charAt(i)) return null;
        }
        if (kindCharOf(d.returnType()) != retSig.charAt(0)) return null;
        return d.handler();
    }

    /**
     * Resolves the LIST codec currently registered for one slot of {@code typeName.method} —
     * {@code argIndex >= 0} for an argument, negative for the return value — or null if that slot no
     * longer holds one (type/method gone, now untyped, arity shrank, codec swapped).
     *
     * <p>Called from a generated wrapper's {@code refresh()}, alongside the handler resolution, for
     * exactly the same reason (see the class doc's Staleness section): the wrapper must not pin the
     * codec object that happened to be registered when it was generated. A LIST slot's SHAPE
     * character is just {@code 'L'}, so {@link #resolveTypedHandler} cannot tell {@code List<Player>}
     * from {@code List<Entity>} — re-fetching the codec by name every mutation is what makes a
     * re-registration with a different element type decode correctly instead of unwrapping against
     * the stale element class and silently yielding an empty list.
     */
    public static PolyType.TypeCodec<?> resolveListCodec(String typeName, String method, int argIndex) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return null;
        PolyType.TypedMethodDescriptor d = type.resolveTypedMethod(method);
        if (d == null) return null;
        PolyType.TypeCodec<?> codec;
        if (argIndex < 0) {
            codec = d.returnType();
        } else {
            if (argIndex >= d.argTypes().size()) return null;
            codec = d.argTypes().get(argIndex);
        }
        return codec instanceof TypeCodecs.WrappedCodec ? codec : null;
    }

    /** Resolves the plain (erased) method handler for {@code typeName.method}, or null. */
    public static PolyType.MethodHandler resolveMethodHandler(String typeName, String method) {
        PolyType type = PolyTypeRegistry.get(typeName);
        return type != null ? type.resolveMethod(method) : null;
    }

    /**
     * The typed handler for {@code typeName.prop}, but ONLY if its currently-registered return kind
     * still matches {@code retSig} — the single kind character the calling wrapper's native accessor
     * was generated for. Any mismatch returns null, which routes that accessor through
     * {@link #genericProperty}. Same contract as {@link #resolveTypedHandler}, one character wide
     * because a property takes no arguments.
     */
    public static Object resolveTypedPropertyHandler(String typeName, String prop, String retSig) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return null;
        PolyType.TypedPropertyDescriptor d = type.resolveTypedProperty(prop);
        if (d == null || retSig.length() != 1) return null;
        if (kindCharOf(d.returnType()) != retSig.charAt(0)) return null;
        return d.handler();
    }

    /** The codec of a typed property, for a wrapper whose return needs decoding inside it (a
     *  {@link TypeCodecs.WrappedCodec}). Re-resolved by name on every refresh, for the same reason
     *  {@link #resolveListCodec} is. */
    public static PolyType.TypeCodec<?> resolveTypedPropertyCodec(String typeName, String prop) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return null;
        PolyType.TypedPropertyDescriptor d = type.resolveTypedProperty(prop);
        return d != null && d.returnType() instanceof TypeCodecs.WrappedCodec ? d.returnType() : null;
    }

    /** Resolves the property handler for {@code typeName.prop}, or null. */
    public static PolyType.PropertyHandler resolvePropertyHandler(String typeName, String prop) {
        PolyType type = PolyTypeRegistry.get(typeName);
        return type != null ? type.resolveProperty(prop) : null;
    }

    /** Generic method dispatch — the fallback a generated method takes when its cached handler is
     *  null. Mirrors what {@code PolyTypeRegistry.callMethod} does, including returning NULL rather
     *  than throwing for an unresolvable member. */
    public static ScriptValue genericCall(String typeName, String method, Object instance, ScriptValue[] args) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return ScriptValue.NULL;
        PolyType.MethodHandler h = type.resolveMethod(method);
        if (h == null) return ScriptValue.NULL;
        List<ScriptValue> list = args == null || args.length == 0
                ? List.of() : new ArrayList<>(Arrays.asList(args));
        ScriptValue r = h.call(instance, list);
        return r != null ? r : ScriptValue.NULL;
    }

    /** {@link #genericCall} for a caller that already holds the boxed arg list (the untyped
     *  wrapper shims, whose own signature takes one). */
    public static ScriptValue genericCallList(String typeName, String method, Object instance,
                                               List<ScriptValue> args) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return ScriptValue.NULL;
        PolyType.MethodHandler h = type.resolveMethod(method);
        if (h == null) return ScriptValue.NULL;
        ScriptValue r = h.call(instance, args != null ? args : List.of());
        return r != null ? r : ScriptValue.NULL;
    }

    /** Generic property dispatch — the {@link #genericCall} equivalent for a property. */
    public static ScriptValue genericProperty(String typeName, String prop, Object instance) {
        PolyType type = PolyTypeRegistry.get(typeName);
        if (type == null) return ScriptValue.NULL;
        PolyType.PropertyHandler h = type.resolveProperty(prop);
        if (h == null) return ScriptValue.NULL;
        ScriptValue r = h.get(instance);
        return r != null ? r : ScriptValue.NULL;
    }
}
